apiVersion: v1
kind: Secret
metadata:
  name: decibel-infrastructure-repo
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <github URL>
  password: <PAT or password>
  username: <UserName>
  project: default