alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      
    hosts:
      - alertmanager.decibel.foo
    paths:
      - /
    tls:
      - secretName: alertmanager-tls-secret
        hosts:
          - alertmanager.decibel.foo

prometheus:
  prometheusSpec:
    resources:
        requests:
          memory: "400Mi"
          cpu: "200m"
        limits:
          memory: "800Mi"
          cpu: "400m"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi

grafana:
  enabled: true
  resources:
    requests:
      memory: "150Mi"
    limits:
      memory: "512Mi"
  admin:
    existingSecret: prometheus-secret
    userKey: PROMETHEUS_ADMIN_USER
    passwordKey: PROMETHEUS_ADMIN_PASSWORD
  
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    hosts:
      - grafana.decibel.foo
    path: /
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - grafana.decibel.foo
  grafana.ini:
    server:
      root_url: https://grafana.decibel.foo
      domain: grafana.decibel.foo