apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret
      containers:
      - name: backend
        image: ghcr.io/decibel-swe/backend:v0.85.4-prerelease0
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: backend-configmap
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/messaging_db
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_WEB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: GOOGLE_WEB_CLIENT_ID
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_WEB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: GOOGLE_WEB_CLIENT_SECRET

        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_DESKTOP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: GOOGLE_DESKTOP_CLIENT_ID
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_DESKTOP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: GOOGLE_DESKTOP_CLIENT_SECRET

        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_MOBILE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: GOOGLE_MOBILE_CLIENT_ID
        
        # Stripe
        - name:  STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: STRIPE_API_KEY

        - name: STRIPE_PRICE_PRO_ID
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: STRIPE_PRICE_PRO_ID

        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: STRIPE_WEBHOOK_SECRET
        
        # Azure Storage
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: AZURE_STORAGE_CONNECTION_STRING

        # Email
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SPRING_MAIL_USERNAME
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SPRING_MAIL_PASSWORD
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: firebase-key-volume
          mountPath: "/etc/firebase"
          readOnly: true
      volumes:
      - name: firebase-key-volume
        secret:
          secretName: firebase-key-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_WEB_REDIRECT_URI: "https://decibel.foo/oauth/callback"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_DESKTOP_REDIRECT_URI: "http://localhost:8081/oauth/callback"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_MOBILE_REDIRECT_URI: "https://decibel.foo/oauth/callback"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_WEB_PROVIDER: "google"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_DESKTOP_PROVIDER: "google"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_MOBILE_PROVIDER: "google"
  SPRING_FLYWAY_ENABLED: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  FIREBASE_SERVICE_ACCOUNT_PATH: "/etc/firebase/firebase-service-account.json"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "backend"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "25"
  SERVER_TOMCAT_THREADS_MAX: "150"