apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret
      containers:
      - name: frontend
        image: ghcr.io/decibel-swe/frontend:v1.34.23-prerelease0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi" 
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env: 
        - name: RECAPTCHA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: RECAPTCHA_SECRET_KEY
        envFrom:
          - configMapRef:
              name: frontend-configmap
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  NEXT_PUBLIC_API_URL: https://decibel.foo/api
  NEXT_PUBLIC_APP_URL: https://decibel.foo
  NEXT_PUBLIC_USE_MOCK: "false"
